# Generated by Django 5.2.15 on 2026-06-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="模型标识名")),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="显示名称"),
                ),
                (
                    "dataset_name",
                    models.CharField(max_length=50, verbose_name="训练数据集"),
                ),
                ("accuracy", models.FloatField(default=0, verbose_name="准确率")),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="模型文件路径"),
                ),
                (
                    "file_size_mb",
                    models.FloatField(default=0, verbose_name="模型大小(MB)"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "模型信息",
                "verbose_name_plural": "模型信息",
                "db_table": "models_info",
                "unique_together": {("name", "dataset_name")},
            },
        ),
    ]
